apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "\e[31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮\e[0m\n\e[31m│\e[0m
      \                                                                                                         \e[31m│\e[0m\n\e[31m│\e[0m
      \   You are trying to run the amd64 binary on an M1 system.                                               \e[31m│\e[0m\n\e[31m│\e[0m
      \   Please consider running the darwin/arm64 binary instead.                                              \e[31m│\e[0m\n\e[31m│\e[0m
      \   Download at https://github.com/kubernetes/minikube/releases/download/v1.27.1/minikube-darwin-arm64
      \   \e[31m│\e[0m\n\e[31m│\e[0m                                                                                                          \e[31m│\e[0m\n\e[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯\e[0m\n192.168.49.2.nip.io"
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
